title: pl
tagline: Paul Le

author:
  name: Paul Le

menu:
- {name: 'About', url: ''}
- {name: 'Projects', url: 'projects.html'}
- {name: 'Blog', url: 'blog.html'}
- {name: 'Contact', url: 'contact.html'}

projects:
- {name: 'Free Code Camp Projects', folder: 'proj-1', file: 'projects/freecodecamp.html'}
- {name: 'Lagrange Jekyll Theme', folder: 'proj-2', file: 'projects/lagrange.html'}
- {name: 'Millennial Jekyll Theme', folder: 'proj-3', file: 'projects/millennial.html'}
- {name: 'Personal Portfolio Website', folder: 'proj-4', file: 'projects/personal-portfolio.html'}
