title: pl
tagline: Paul Le

author:
  name: Paul Le

menu:
- {name: 'About', url: ''}
- {name: 'Projects', url: 'projects.html'}
- {name: 'Blog', url: 'blog.html'}
- {name: 'Contact', url: 'contact.html'}

projects:
- {name: 'Physics in Motion', image: 'run.jpg', file: 'projects/physics-in-motion.html'}
- {name: 'applepy', image: 'gun.jpg', file: 'projects/applepy.html'}
- {name: 'Jekyll Themes', image: 'box.jpg', file: 'projects/jekyll-themes.html'}
