title: pl
tagline: Paul Le

author:
  name: Paul Le

menu:
- {name: 'About', url: ''}
- {name: 'Projects', url: 'projects.html'}
- {name: 'Blog', url: 'blog.html'}
- {name: 'Contact', url: 'contact.html'}
