title: pl
tagline: Paul Le

author:
  name: Paul Le

menu:
- {name: 'About', url: ''}
- {name: 'Projects', url: 'projects.html'}
- {name: 'Blog', url: 'blog.html'}
- {name: 'Contact', url: 'contact.html'}

projects:
- {name: 'Physics in Motion', folder: 'proj-1', file: 'projects/physics-in-motion.html'}
- {name: 'applepy', folder: 'proj-2', file: 'projects/applepy.html'}
- {name: 'Jekyll Themes', folder: 'proj-3', file: 'projects/jekyll-themes.html'}
